=== Rodez-IUT/dut-info2-filmprovider-Scouike/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ELEMENT librairie (entete,livre)>
    <!ELEMENT entete (%balise;)>
    <!ENTITY entete "&#xA9;Librairie &amp; Internet 2020">
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT img EMPTY>
            <!ATTLIST img src CDATA #REQUIRED>
            <!ATTLIST img title CDATA #IMPLIED>


    <!ELEMENT livre (titre,auteur+|collectif,description,prix)>
        <!ELEMENT titre (#PCDATA)>
        <!ELEMENT auteur (%identite;)>
            <!ELEMENT nom (#PCDATA)>
            <!ELEMENT prenom (#PCDATA)>
        <!ELEMENT collectif (direction,membres)
            <!ELEMENT direction (%identite;)>
            <!ELEMENT membres (txtLibre)>
                <!ELEMENT txtLibre (#PCDATA)>
        <!ELEMENT description (%balise;)>
        <!ELEMENT prix (valeur)>
            <!ELEMENT valeur (#PCDATA)>
            <!ATTLIST prix tva #FIXED "5,5">
            <!ATTLIST prix devise (euro|livre|dollars) "euro">
            <!ATTLIST prix taxe (HT|TTC) "HT">
        <!ATTLIST livre ISBN NMTOKENS #REQUIRED>
    <!ENTITY % balise "(#PCDATA|strong|em|img)*">
    <!ENTITY % identite "(nom,prenom?)">

=== Rodez-IUT/dut-info2-filmprovider-Scouike/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <entete>Librairie donnée en <strong>exemple</strong>.</entete>
    <livre ISBN="12345">
        <titre>Enseigner le XML</titre>
        <auteur>
                <nom>Paul Dumond</nom>
        </auteur>
        <description>Ce livre parle de l'enseignement du XML.</description>
        <prix devise="euro" tva="5.5" taxe="TTC">12</prix>
    </livre>
    <livre ISBN="67890">
        <titre>Enseigner le Java</titre>
        <collectif>
            <direction>
                <nom>Developpeurs associés</nom>
            </direction>
            <membres>Valérie Durand, Émilie Favin et Paul Dumond</membres>
        </collectif>
        <description> Apprendre <em>Java</em> en s'amusant !. <img src="img.jpg"/></description>
        <prix taxe="TTC" devise="euro" tva="5.5">24</prix>
    </livre>
</librairie>
